#!/bin/bash

set -e # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables

export PATH=$PATH:/var/vcap/packages/dea_jvm7/bin
# Setup cassandra conf from jobs directory
export CASSANDRA_CONF=/var/vcap/jobs/cassandra_node/conf

RUN_DIR=/var/vcap/sys/run/cassandra_node
LOG_DIR=/var/vcap/sys/log/cassandra_node
PIDFILE=$RUN_DIR/cassandra.pid
JOB_DIR=/var/vcap/jobs/cassandra_node


source /var/vcap/packages/common/utils.sh

# Setup env vars and folders for the webapp_ctl script
#source /var/vcap/jobs/cassandra_node/helpers/ctl_setup.sh 'cassandra_node'
# Don't think I like these ctl_setup helpers - don't think it allows me to have server and node ctls in the same directory.  
#  ... Still have to follow through on this one.

export PORT=${PORT:-5000}
export LANG=en_US.UTF-8


case $1 in

  start)
    pid_guard $PIDFILE "Cassandra"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    /var/vcap/packages/cassandra/bin/cassandra -p $PIDFILE -Dcassandra.rpc_port=<%=properties.cassandra.port%> \ 
         >>$LOG_DIR/cassandra.stdout.log \
         2>>$LOG_DIR/cassandra.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;
  *)
    echo "Usage: cassandra_ctl {start|stop}"

    ;;

esac
exit 0
